blog/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
# from django.contrib.auth.views import logout_then_login
from django.contrib.auth import views as auth_views
from .views import *
from .view.experience import *
from .view.registration import *
from .view.education import *
from .view.certificate import *
from .view.skills import *
from .view.profile import *
from .view.friends import *

# from .view.user_page import *

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login/$', LoginView.as_view(template_name='blog/registration/login.html'), name='login'),
    url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
    # url(r'^register/$', RegistrationView.as_view(), name='register'),
    url(r'^register/$', register, name='register'),
    url(r'^user/?$', HomeView.as_view(), name='user_page_url'),
    url(r'^user/(\d+)/?$', HomeView.as_view(), name='user_page_url'),  # Заменить на UserView из view.user_page.py

    url(r'^experiences/?$', ExperienceView.as_view(), name='experience_index'),  # index, create
    url(r'^experiences/new/?$', ExperienceView.as_view(), name='experience_new'),  # new
    url(r'^experiences/(\d+)/?$', ExperienceView.as_view(), name='experience_show'),  # show, update, destroy
    url(r'^experiences/(\d+)/edit/?$', ExperienceView.as_view(), name='experience_edit'),  # edit
    # url(r'^experiences/(\d+)/?$', ExperienceView.as_view(), name='experience_update'),  # update, destroy

    url(r'^education/?$', EducationView.as_view(), name='education_index'),  # index, create
    url(r'^education/new/?$', EducationView.as_view(), name='education_new'),  # new
    url(r'^education/(\d+)/?$', EducationView.as_view(), name='education_show'),  # show, update, destroy
    url(r'^education/(\d+)/edit/?$', EducationView.as_view(), name='education_edit'),  # edit

    url(r'^certificate/?$', CertificateView.as_view(), name='certificate_index'),  # index, create
    url(r'^certificate/new/?$', CertificateView.as_view(), name='certificate_new'),  # new
    url(r'^certificate/(\d+)/?$', CertificateView.as_view(), name='certificate_show'),  # show, update, destroy
    url(r'^certificate/(\d+)/edit/?$', CertificateView.as_view(), name='certificate_edit'),  # edit

    url(r'^skill/?$', SkillView.as_view(), name='skill_index'),  # index, create
    url(r'^skill/new/?$', SkillView.as_view(), name='skill_new'),  # new
    url(r'^skill/(\d+)/?$', SkillView.as_view(), name='skill_show'),  # show, update, destroy
    url(r'^skill/(\d+)/edit/?$', SkillView.as_view(), name='skill_edit'),  # edit

    url(r'^profile/(\d+)/?$', ProfileView.as_view(), name='profile_index'),  # index, create
    url(r'^profile/new/?$', ProfileView.as_view(), name='profile_new'),  # new
    url(r'^profile/(\d+)/?$', ProfileView.as_view(), name='profile_show'),  # show, update, destroy
    url(r'^profile/(\d+)/edit/?$', ProfileView.as_view(), name='profile_edit'),  # edit

    url(r'^friend/$', FriendView.as_view(), name='friends'),
    url(r'^friend/(?P<operation>.+)/(?P<id>\d+)/$', FriendView.change_friends, name='change_friends'),
    url(r'^user/friend/(\d+)/show/?$', FriendView.as_view(), name='show_friend_page'),
]

simple_site/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django_fields import DefaultStaticImageField
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=150)
    location = models.CharField(max_length=30)
    e_mail = models.EmailField(null=True, blank=True, default='')
    phone = models.CharField(max_length=20, blank=True)
    web_sites = models.URLField(max_length=200, blank=True)
    common_information = models.TextField(max_length=500, blank=True)
    profile_image = DefaultStaticImageField(blank=True, null=True, default_image_path='img/blog/unnamed.jpg')


@receiver(post_save, sender=User)
def create_user_profile(instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance, first_name=instance.first_name, last_name=instance.last_name)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name="owner", null=True, on_delete=models.CASCADE)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

    def __str__(self):
        return str(self.current_user)


class Experience(models.Model):
    position = models.CharField(max_length=50)
    type_employment = models.CharField(max_length=2, null=True)
    company = models.CharField(max_length=100, null=True)
    region = models.CharField(max_length=50, blank=True)
    checkbox = models.BooleanField(blank=True, default=False)
    date_start = models.DateField(default=datetime.now, null=True)
    date_end = models.DateField(default=datetime.now, null=True)
    description = models.TextField(blank=True, null=True)

    user = models.ForeignKey(User, related_name='experiences_created', on_delete=models.CASCADE)


class Education(models.Model):
    institution = models.CharField(max_length=100)
    degree = models.CharField(max_length=100, blank=True)
    specialization = models.CharField(max_length=100, blank=True)
    date_start = models.DateField(default=datetime.now, blank=True)
    date_end = models.DateField(default=datetime.now, blank=True)
    description = models.TextField(blank=True)

    user = models.ForeignKey(User, related_name='education_created', on_delete=models.CASCADE)


class Certificate(models.Model):
    name = models.CharField(max_length=150)
    department = models.CharField(max_length=150)
    date_start = models.DateField(default=datetime.now, blank=True)
    url_address = models.CharField(max_length=150, blank=True)

    user = models.ForeignKey(User, related_name='certificate_created', on_delete=models.CASCADE)


class Skill(models.Model):
    name = models.CharField(max_length=150)
    user = models.ForeignKey(User, related_name='skill_created', on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import *
from django.views import View
from .form.experience import ExperienceForm


@login_required
def dashboard(request):
    return render(request, 'blog/dashboard.html')


class HomeView(View):
    def get(self, request, id=None):
        if id is None:
            return render(request, 'blog/user_page.html')
        else:
            user = User.objects.get(id=id)
            return render(request, 'blog/user_page.html', {'user': user})

blog/templates/blog/certificates/edit.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document" data-controller="certificate--edit"
     data-experience-id={{ object.id }}>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit certificate</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="certificateFormEdit" method="POST" action="{% url 'blog:certificate_show' object.id %}">
                <input type="hidden" name="_method" value="PATCH">

                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button form="certificateFormEdit" id="certificate-btn-edit" class="btn buttons float-right"
                    type="submit" value="Send">Update
            </button>
        </div>
    </div>
</div>

blog/templates/blog/certificates/new.html
<div id="modal-certificate-new" class="modal-dialog modal-dialog-scrollable modal-lg" role="document" data-controller="certificate--new">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create certificate</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="certificateFormNew" method="post" action="{% url 'blog:certificate_new' %}">

                {% csrf_token %}

                {% for field in form_certificate %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button form="certificateFormNew" id="certificate-btn-new" class="btn buttons float-right"
                    type="submit" value="Send">Add
            </button>
        </div>
    </div>
</div>

blog/templates/blog/education/edit.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document" data-controller="education--edit"
     data-experience-id={{ object.id }}>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit education</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>

        <div class="modal-body">

            <form id="educationFormEdit" method="POST" action="{% url 'blog:education_show' object.id %}">
                <input type="hidden" name="_method" value="PATCH">

                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button form="educationFormEdit"  id="education-btn-edit" class="btn buttons float-right"
                    type="submit" value="Send">Update
            </button>
        </div>
    </div>
</div>

blog/templates/blog/education/new.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document" data-controller="education--new">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create education</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="educationFormNew" method="post" action="{% url 'blog:education_index' %}">

                {% csrf_token %}

                {% for field in form_education %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button form="educationFormNew" id="education-btn-new" class="btn buttons float-right"
                    type="submit" value="Send">Add
            </button>
        </div>
    </div>
</div>

blog/templates/blog/experiences/edit.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document" data-controller="experience--edit"
     data-experience-id={{ object.id }}>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit experience</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="experienceFormEdit" method="POST" action="{% url 'blog:experience_show' object.id %}">
                <input type="hidden" name="_method" value="PATCH">

                {% csrf_token %}

                {% for field in exp_form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button form="experienceFormEdit" id="experience-btn-edit" class="btn buttons float-right"
                    type="submit" value="Send">Update
            </button>
        </div>
    </div>
</div>

blog/templates/blog/experiences/new.html
<div id="modal-experience-new" class="modal-dialog modal-dialog-scrollable modal-lg" role="document"
     data-controller="experience--new">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create experience</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="experienceFormNew" method="post" action="{% url 'blog:experience_new' %}">

                {% csrf_token %}

                {% for field in form_experience %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>

                {% endfor %}
            </form>

            <button form="experienceFormNew" id="experience-btn-new" class="btn buttons float-right"
                    type="submit" value="Send">Add
            </button>
        </div>
    </div>
</div>

blog/templates/blog/experiences/update.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit experience</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="experienceForm" method="post" action="{% url 'blog:experience_edit' object.id %}">

                {% csrf_token %}

                {% for field in exp_form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button form="experienceForm" class="btn btn-outline-success" id="modal-experience-btn"
                    type="submit" value="Send">Update
            </button>
        </div>
    </div>
</div>

blog/templates/blog/friends/index.html
{% load static %}
<section class="section about-section gray-bg mb-3" id="about" data-controller="friend--index">

    <div class="container">
        <h3>All users</h3>
        {% for user in users %}
            {% if user.is_staff == False %}
                <nav class="navbar navbar-friend navbar-light bg-light mb-2">
                    <a class="navbar-brand" href='{% url 'blog:user_page_url' user.id %}'>
                        <img src="{{ user.profile.profile_image.url }}" width="30" height="30"
                             class="d-inline-block align-top">
                        {% if user.first_name or user.last_name %}
                            {{ user.first_name }}
                            <p>{{ user.last_name }}</p>
                        {% else %}
                            <p>{{ user.username }}</p>
                        {% endif %}
                    </a>


                    {% if not user in friends %}
                        <a href="{% url 'blog:change_friends' operation='add' id=user.id %}">
                            <button type="button" class="btn buttons">
                                Add
                            </button>
                        </a>
                    {% endif %}
                </nav>
            {% endif %}
        {% endfor %}
    </div>

</section>

<section class="section about-section gray-bg mb-3">
    <div class="container">
        <h3>Friends</h3>

        {% for friend in friends %}
            <nav class="navbar navbar-friend navbar-light mb-2">
                <a class="navbar-brand" href='{% url 'blog:user_page_url' friend.id %}'>
                    <img src="{{ friend.profile.profile_image.url }}" width="30" height="30"
                         class="d-inline-block align-top">

                    {% if friend.first_name or friend.last_name %}
                        {{ friend.first_name }}
                        {{ friend.last_name }}
                    {% else %}
                        {{ friend.username }}
                    {% endif %}
                </a>
                <a href="{% url 'blog:change_friends' operation='remove' id=friend.id %}">
                    <button type="button" class="btn buttons">
                        Remove
                    </button>
                </a>
            </nav>
        {% endfor %}
    </div>
</section>

blog/templates/blog/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>My Job</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

    {# jQuery #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    {# Bootstrap #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    {# FontAwesome #}
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" href="/blog/static/libs/font/fontawesome.min.css"/>

    {# Toastr #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    {# StimulusJS #}
    <script src="https://unpkg.com/stimulus/dist/stimulus.umd.js"></script>

    {# Custom styles #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">

    {#    js-cookie#}
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>

    {#    sweetalert#}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

</head>

<body>

<header>
    {% if request.user.is_authenticated %}

        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#2d6dc273;">
{#                8ba3c7#}

                <div class="navbar-nav">
                    <a class="text-dark" href="{% url 'blog:user_page_url' %}">Profile</a>
                </div>
                <a class="navbar-logo center" href="{% url 'blog:dashboard' %}">
                    <img src="{% static 'img/blog/logo.png' %}">
                </a>
                <div class="nav-user">
                    <button type="button" class="btn navbar-light buttons">
                        <a class="buttons"
                            href="{% url 'blog:logout_then_login' %}">Log out</a></button>
                </div>

            </nav>
        </div>

    {% endif %}


</header>

<section>
    <div class="container">
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>

</section>


<footer class="footer">
    <div class="container">
        <div class="text">
        </div>
    </div>
</footer>


<div data-controller="modal" class="modal" id="modal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLongTitle"
     aria-hidden="true">

</div>

<script type="module" src="{% static 'js/index.js' %}"></script>


</body>
</html>

blog/templates/blog/profile/edit.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document" data-controller="profile--edit"
     data-experience-id={{ object.id }}>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit profile</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form enctype="multipart/form-data" id="profileFormEdit" method="POST"
                  action="{% url 'blog:profile_show' object.id %}">
                <input type="hidden" name="_method" value="PATCH">

                {% csrf_token %}

                <div class="box">
                    <div>
                        {% for field in form %}
                            <div class="box-item">
                                {% if field.errors %}
                                    <div class="alert alert-danger">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}

                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </form>
            <button form="profileFormEdit" id="profile-btn-edit" class="btn buttons float-right flex-elem"
                    type="submit" value="Send">Update
            </button>
        </div>
    </div>
</div>

blog/templates/blog/profile/new.html
<div id="modal-profile-new" class="modal-dialog modal-dialog-scrollable modal-lg" role="document"
     data-controller="profile--new">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit profile</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="profileFormNew" method="post" action="{% url 'blog:profile_new' %}">

                {% csrf_token %}

                {% for field in form_profile %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button form="profileFormNew" id="profile-btn-new" class="btn btn-outline-success float-right"
                    type="submit" value="Send">Save
            </button>
        </div>
    </div>
</div>

blog/templates/blog/skills/edit.html
<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document" data-controller="certificate--edit"
     data-experience-id={{ object.id }}>

    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit certificate</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span class="modal-close" aria-hidden="true">&times</span>
            </button>
        </div>
        <div class="modal-body">

            <form id="certificateFormEdit" method="POST" action="{% url 'blog:certificate_show' object.id %}">
                <input type="hidden" name="_method" value="PATCH">

                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}

            </form>
            <button form="certificateFormEdit" id="certificate-btn-edit" class="btn buttonsfloat-right"
                    type="submit" value="Send">Update
            </button>
        </div>
    </div>
</div>

blog/templates/blog/skills/index.html
<div class="card" data-controller="skill--index">
    <h5 class="card-header" style='background-color:#b1baec21;'>
        Skills & Technologies
    </h5>
    <div class="card-body ">
        <form method="POST" action="{% url 'blog:skill_index' %}">
            {% csrf_token %}

            <div class="row">

                <div class=" col-10 pr-0">

                    {% for field in form_skills %}
                        {% if field.errors %}
                            <div class="alert alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {{ field }}
                    {% endfor %}
                </div>

                <div class="col-2 pr-0">
                    <button class="btn buttons mt-2 p-lg-2" value="Send" type="submit"> Add
                    </button>
                </div>
            </div>

            <div class="row">
                {% for skill in skills %}
                    <div class="skill-name col-3 d-flex flex-row justify-content-center border mx-4 mr-2 my-2" style='background-color:#b1baec21;'
                         data-id={{ skill.id }}>
                        <p class="mb-1 mr-2">{{ skill.name }}</p>

                        <i class="fas fa-trash mt-1"
                           data-action="click->skill--index#deleteObject"></i>
                    </div>
                {% endfor %}
            </div>

        </form>
    </div>


</div>

blog/templates/blog/user_page.html
{% extends 'blog/index.html' %}
{% load static %}

{% block content %}

    <div class="row">
        <!-- MAIN -->
        <main class="col-md-8 col-lg-9">


            <div class="card card-body">
                <div data-load=true data-url="{% url 'blog:profile_index' user.profile.id %}" data-controller="profile--index">
                </div>

                <div data-load=true data-url="/experiences?user_id={{ user.id }}" data-controller="experience--index">
                </div>

                <div data-load=true data-url="/education?user_id={{ user.id }}" data-controller="education--index">
                </div>

                <div data-load=true data-url="/certificate?user_id={{ user.id }}" data-controller="certificate--index">
                </div>

                <div data-load=true data-url="/skill?user_id={{ user.id }}" data-controller="skill--index">
                </div>

            </div>

        </main>

        <!-- ASIDE -->
        <div class="col-md-4 col-lg-3">
            <div class="row">
                <!-- ASIDE #1 -->
                <aside class="col-sm-6 col-md-12">
                    <div data-load=true data-controller="friend--index">
                    </div>
                </aside>

                <!-- ASIDE #2 -->
                <aside class="col-sm-6 col-md-12">
                </aside>
                <div class="row">
                </div>
            </div>
        </div>
    </div>


{% endblock %}